name: initialize

on:
  push:
    branches:
    - master

env:
  TEMPLATE_OWNER: juliendargelos
  TEMPLATE_NAME: rollup-library

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check repository
      id: repository
      run: echo ::set-output name=type::$((( $(git rev-list --count HEAD) < 2 )) && echo instance || echo template)
    - name: Test
      if: steps.repository.outputs.type == 'instance'
      run: echo This should not appear when ran from template repository
    # - name: Replace repository and package name
    #   if: steps.repository.outputs.type == 'instance'
    #   run: |
    #     sed -i "s#${TEMPLATE_OWNER}/${TEMPLATE_NAME}#${{github.repository}}#g" package.json readme.md
    #     sed -i "s#${TEMPLATE_NAME}#${{github.event.repository.name}}#g" package.json readme.md
    # - name: Remove template related content
    #   if: steps.repository.outputs.type == 'instance'
    #   run: |
    #     sed -i 's#"description":.*#"description": "",#' package.json
    #     sed -i '1,6!d' readme.md
    # - name: Clean
    #   if: steps.repository.outputs.type == 'instance'
    #   run: rm .github/workflows/initialize.yml
    # - name: Push changes
    #   if: steps.repository.outputs.type == 'instance'
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add --all
    #     git commit -m "Initialize package"
    #     git push "https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git" HEAD:master
